### PR TITLE
fix(issue-640): adding headers in task request samples

### LINKED ISSUE #640: Documentation/Examples should include `Content-Type` header
Hi Guys, the examples omit the `Content-Type` header for the httpRequest while using POST body. Many http frameworks will ignore the POST body if no Content-Type-Request-Header is set. I think its bad practice to provide examples that probably wont work as expected because that header is missing. 

#### Environment details

  - OS: GCF
  - Node.js version: 16
  - npm version: 8.13.2
  - `@google-cloud/tasks` version: ^3.0.0

#### Steps to reproduce

  1. follow example
  2. receive no `req.body` in URL that's being called (in my case a GCF using the node/http variety (express))

### PR DESCRIPTION
**Pull request by pattishin**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-tasks/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #640  🦕

Affects:
 - https://cloud.google.com/tasks/docs/creating-http-target-tasks
 - https://cloud.google.com/run/docs/triggering/using-tasks

### CODE REVIEW

File: samples/createHttpTask.js [hunk 1]
```diff
@@ -51,6 +51,9 @@ function main(
 
     const task = {
       httpRequest: {
+        headers: {
+          'Content-Type': 'application/json',
```
Comment (averikitsch) [inline samples/createHttpTask.js:55]: This doesn't match the sample. The sample checks down below if there is even a payload. The example payload is a string or 'text/plain' not json.

**Review by averikitsch — CHANGES_REQUESTED** [review]

File: samples/createHttpTask.js (hunk 1 above)
Comment (pattishin) [reply samples/createHttpTask.js:55]: Ty for catching this!

**Review by averikitsch — APPROVED** [review]
